baseURL = 'https://taynguyentruong.github.io/nguyentruongsontay/'
title = 'Nguyễn Trường Sơn Tây'
theme = 'adritian-free-hugo-theme'
languageCode = 'vi'

[params]
  author = "Nguyễn Trường Sơn Tây"
  description = "Chào mừng bạn đến với blog của tôi. Tôi đam mê Java, JavaScript và Network Programming."
  images = ["img/avatar.png"]
  
  # Adritian settings
  homepageExperienceCount = 6
  
  [params.blog]
    layout = "sidebar-right"
    sidebarWidth = "25"
    narrowContent = true
    showCategories = true
    showRecentPosts = true
    recentPostCount = 5
    listStyle = "summary"
    listLayout = "default"

[languages]
  [languages.vi]
    languageName = "Tiếng Việt"
    contentDir = "content"
    weight = 1
    
    [languages.vi.menus]
      [[languages.vi.menus.header]]
        name = "Trang chủ"
        URL = "/"
        weight = 1
      [[languages.vi.menus.header]]
        name = "Về tôi"
        URL = "/#about"
        weight = 2
      [[languages.vi.menus.header]]
        name = "Blog"
        URL = "/posts/"
        weight = 3
      [[languages.vi.menus.header]]
        name = "Liên hệ"
        URL = "/contact/"
        weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    style = "github"
