baseURL = 'https://taynguyentruong.github.io/nguyentruongsontay/'
title = 'Nguyễn Trường Sơn Tây'
languageCode = 'vi'
theme = 'congo'
defaultContentLanguage = 'vi'

[metadata]
  # Enables minimal mode
  # minimal = true
  
[params]
  colorScheme = "congo" # options: "congo", "avocado", "ocean", "slate", ...
  defaultTheme = "light"
  
  [params.profile]
    show = true
    name = "Nguyễn Trường Sơn Tây"
    image = "img/avatar.png"
    headline = "Sinh viên Lập trình Mạng"
    bio = "Chào mừng bạn đến với blog của tôi. Tôi đam mê Java, JavaScript và Network Programming."
    links = [
      { icon = "github", url = "https://github.com/taynguyentruong" },
      { icon = "facebook", url = "https://www.facebook.com/nguyen.truong.son.tay" },
      { icon = "email", url = "mailto:taynguyen12032003@gmail.com" }
    ]

  [params.footer]
    showCopyright = true
    showTheme = false
    showPoweredBy = false

[languages]
  [languages.vi]
    languageName = "Tiếng Việt"
    contentDir = "content"
    weight = 1

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Về tôi"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "contact"
    name = "Liên hệ"
    url = "/contact/"
    weight = 30
