baseURL = 'https://taynguyentruong.github.io/nguyentruongsontay/'
languageCode = 'vi'
title = 'Nguy·ªÖn Tr∆∞·ªùng S∆°n T√¢y - Blog'
theme = 'PaperMod'

[params]
  defaultTheme = "light"
  env = "production"
  description = "Blog chia s·∫ª v·ªÅ L·∫≠p tr√¨nh m·∫°ng, Java v√† JavaScript"
  author = "Nguy·ªÖn Tr∆∞·ªùng S∆°n T√¢y"
  # ShowReadingTime = true
  # ShowShareButtons = true
  
  [params.profileMode]
    enabled = false
    title = "Nguy·ªÖn Tr∆∞·ªùng S∆°n T√¢y"
    subtitle = "Sinh vi√™n L·∫≠p tr√¨nh M·∫°ng"
    # imageUrl = "<link to your image>"
    
  [params.homeInfoParams]
    Title = "Xin ch√†o üëã"
    Content = "Ch√†o m·ª´ng b·∫°n ƒë·∫øn v·ªõi blog c√° nh√¢n c·ªßa t√¥i. N∆°i chia s·∫ª ki·∫øn th·ª©c v·ªÅ l·∫≠p tr√¨nh Java, JavaScript v√† L·∫≠p tr√¨nh m·∫°ng."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/taynguyentruong"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "Profile"
    url = "/about"
    weight = 30
