baseURL = 'https://taynguyentruong.github.io/nguyentruongsontay/'
title = 'Nguyễn Trường Sơn Tây'
theme = 'hugo-theme-gruvbox'
defaultContentLanguage = 'vi'
languageCode = 'vi'

enableRobotsTXT = true

[build]
  noJSConfigInAssets = true
  [build.buildStats]
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Nguyễn Trường Sơn Tây"
  image = "img/avatar.png"
  description = "Chào mừng bạn đến với blog của tôi. Tôi đam mê Java, JavaScript và Network Programming."
  defaultTheme = "light"
  
  [params.logo]
    text = "Nguyễn Trường Sơn Tây"
    url = "/"

  [params.prism]
    languages = ["markup", "css", "clike", "javascript", "bash", "java"]
    plugins = ["normalize-whitespace", "toolbar", "copy-to-clipboard", "line-numbers"]

[languages]
  [languages.vi]
    languageName = "Tiếng Việt"
    contentDir = "content"
    weight = 1

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Về tôi"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "contact"
    name = "Liên hệ"
    url = "/contact/"
    weight = 30
