baseURL = 'https://taynguyentruong.github.io/nguyentruongsontay/'
title = 'Nguyễn Trường Sơn Tây'
theme = 'adritian-free-hugo-theme'
languageCode = 'vi'

[params]
  author = "Nguyễn Trường Sơn Tây"
  description = "Xin chào! Tôi là Nguyễn Trường Sơn Tây, sinh viên Công nghệ Thông tin tại HUTECH. Blog chia sẻ kiến thức về lập trình Java, JavaScript và Network Programming."
  images = ["img/avatar.png"]
  
  # Adritian settings
  homepageExperienceCount = 6
  
  [params.experience]
    showJobCard = true

  [params.blog]
    layout = "sidebar-right"
    sidebarWidth = "25"
    narrowContent = true
    showCategories = true
    showRecentPosts = true
    recentPostCount = 5
    listStyle = "summary"
    listLayout = "default"

  # Plugins
  [params.plugins]
    # CSS Plugins
    [[params.plugins.css]]
      URL = "css/custom.css"
    [[params.plugins.css]]
      URL = "css/adritian-icons.css"
    ## Print css
    [[params.plugins.css]]
      URL = "css/bootstrap-print.css"
    
    # JS Plugins
    [[params.plugins.js]]
      URL = "js/rad-animations.js"
    [[params.plugins.js]]
      URL = "js/sticky-header.js"
    [[params.plugins.js]]
      URL = "js/library/fontfaceobserver.js"
    
    # SCSS Plugins
    [[params.plugins.scss]]
      URL = "scss/adritian.scss"

  [params.colorTheme]
    [params.colorTheme.selector.disable]
      footer = false
      header = false
      mobileHeader = false

  [params.pageTransition]
    enabled = true

[languages]
  [languages.vi]
    languageName = "Tiếng Việt"
    contentDir = "content"
    weight = 1
    
    [languages.vi.menus]
      [[languages.vi.menus.header]]
        name = "Trang chủ"
        URL = "/"
        weight = 1
      [[languages.vi.menus.header]]
        name = "Về tôi"
        URL = "/#about"
        weight = 2
      [[languages.vi.menus.header]]
        name = "Kinh nghiệm"
        URL = "/#experience"
        weight = 3
      [[languages.vi.menus.header]]
        name = "Dự án"
        URL = "/#client-and-work-section"
        weight = 4
      [[languages.vi.menus.header]]
        name = "Blog"
        URL = "/posts/"
        weight = 5
      [[languages.vi.menus.header]]
        name = "Liên hệ"
        URL = "/contact/"
        weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    style = "github"
